'use client';

import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';

// Generated by scripts/bake-printer-environment.mjs. This is the same studio
// lighting, already filtered, so visitors do not have to run PMREM generation.
class PrinterEnvironmentLoader extends THREE.Loader<THREE.DataTexture> {
  load(url: string, onLoad: (texture: THREE.DataTexture) => void, onProgress?: (event: ProgressEvent) => void, onError?: (error: unknown) => void) {
    const loader = new THREE.FileLoader(this.manager);
    loader.setResponseType('arraybuffer');
    loader.load(url, async data => {
      try {
        const source = data as ArrayBuffer;
        const compressed = new Uint8Array(source);
        // Also accept a response the host has already decompressed.
        const buffer = compressed[0] === 0x1f && compressed[1] === 0x8b
          ? await new Response(new Blob([source]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()
          : source;
        const header = new DataView(buffer);
        const width = header.getUint32(4, true), height = header.getUint32(8, true);
        if (header.getUint32(0, true) !== 0x31505349 || buffer.byteLength !== 12 + width * height * 8) {
          throw new Error('Invalid printer studio texture');
        }
        const texture = new THREE.DataTexture(new Uint16Array(buffer, 12), width, height, THREE.RGBAFormat, THREE.HalfFloatType);
        texture.mapping = THREE.CubeUVReflectionMapping;
        texture.minFilter = texture.magFilter = THREE.LinearFilter;
        texture.colorSpace = THREE.LinearSRGBColorSpace;
        texture.needsUpdate = true;
        onLoad(texture);
      } catch (error) { onError?.(error); }
    }, onProgress, onError);
  }
}

export default function PrinterEnvironment() {
  const texture = useLoader(PrinterEnvironmentLoader, '/models/printer-studio.bin.gz');
  return <primitive object={texture} attach="environment"/>;
}
