'use client';

import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';
import { PRINTER_STUDIO, printerAsset } from '../../lib/printer-assets';

// Generated by scripts/bake-printer-environment.mjs. This is the same studio
// lighting, already filtered, so visitors do not have to run PMREM generation.
function build(buffer: ArrayBuffer) {
  const header = new DataView(buffer);
  const width = header.getUint32(4, true), height = header.getUint32(8, true);
  if (header.getUint32(0, true) !== 0x31505349 || buffer.byteLength !== 12 + width * height * 8) {
    throw new Error('Invalid printer studio texture');
  }
  const texture = new THREE.DataTexture(new Uint16Array(buffer, 12), width, height, THREE.RGBAFormat, THREE.HalfFloatType);
  texture.mapping = THREE.CubeUVReflectionMapping;
  texture.minFilter = texture.magFilter = THREE.LinearFilter;
  texture.colorSpace = THREE.LinearSRGBColorSpace;
  texture.needsUpdate = true;
  return texture;
}

class PrinterEnvironmentLoader extends THREE.Loader<THREE.DataTexture> {
  load(url: string, onLoad: (texture: THREE.DataTexture) => void, onProgress?: (event: ProgressEvent) => void, onError?: (error: unknown) => void) {
    // The download is already in flight from the page's own bundle.
    printerAsset(url).then(buffer => onLoad(build(buffer))).catch(error => onError?.(error));
  }
}

export default function PrinterEnvironment() {
  const texture = useLoader(PrinterEnvironmentLoader, PRINTER_STUDIO);
  return <primitive object={texture} attach="environment"/>;
}
