export type Guide = {
  slug: string; title: string; summary: string; category: string;
  image: string; project: string; service: string; serviceLabel: string; enquiryRoute?: string;
  sections: { id: string; title: string; paragraphs: string[]; points?: string[] }[];
};
const occasionGuides: Guide[] = [
  {
    slug: 'personalised-baby-shower-keepsakes', title: 'Personalised baby shower keepsakes: choosing a design and planning your order',
    summary: 'Separate guest favours from a gift for the parents, then plan the wording, quantity, presentation and delivery of your baby shower keepsakes.',
    category: 'BABY SHOWERS', image: 'gift-boxes', project: 'personalised-gift-boxes',
    service: 'bonbonniere-custom', serviceLabel: 'Discuss personalised keepsakes', enquiryRoute: 'bulk',
    sections: [
      { id: 'recipients', title: 'Guest favour or gift for the parents?', paragraphs: ['Start with who receives the piece. A favour for every guest needs a clear quantity and a presentation that is easy to hand out. A keepsake for the parents may have different wording, dimensions and packaging. Keep those requirements separate in your brief.', 'For guest favours, decide whether you are ordering per person, couple or household. Include any extras in the requested total. Our bulk orders start at 10 units; ask about the scope of any separate parent gift when discussing the batch.'] },
      { id: 'design', title: 'Choose a design around its intended use', paragraphs: ['A small sculptural object, a personalised tag or a presentation box can each play a different part in the celebration. Send a reference and explain whether you want a display keepsake, an item on each place setting or packaging for a gift you will supply. A photograph is a starting point for discussion, not confirmation that every material or detail can be reproduced.', 'Consider where the keepsake will go after the event and how guests will carry it home. Include dimensions and any packaging constraints. Describe decorative pieces as decoration in your brief; suitability for play, food contact or another special use needs to be established separately.'] },
      { id: 'wording', title: 'Plan wording that can be approved in time', paragraphs: ['Tell us whether the design uses a family name, a short thank-you message, a shower date or individual guest names. If the baby’s name or another detail is not yet decided, mark it as pending and discuss when it must be finalised.', 'Send one checked wording list, including spelling and punctuation. Identify which details repeat across the batch and which change. If family members are helping with approval, choose one person to send the consolidated response.'] },
      { id: 'presentation', title: 'Budget for the finished presentation', paragraphs: ['State whether your budget covers the pieces alone or also includes tags, ribbon, boxes, assembly and freight. For a larger guest list, ask about simplifying the design or reducing variations while keeping the detail that matters to you.', 'Tell us the delivery postcode, event date and the earlier date you need the order in hand. Leave time for your own checking and setup. Materials, finish, availability, pricing and production timing are confirmed after the studio reviews the brief.'] },
      { id: 'brief', title: 'What to send with your enquiry', paragraphs: ['You can begin with an estimate and a reference image. Mark undecided details clearly.'], points: ['Who receives each piece and the quantity required', 'Reference design, intended use and approximate size', 'Shared wording and any individual names', 'Colours, finish and packaging preferences', 'Budget scope, delivery postcode and required arrival date'] },
    ],
  },
  {
    slug: 'personalised-wedding-bonbonniere', title: 'Personalised wedding bonbonniere: ideas, guest quantities and presentation',
    summary: 'Choose wedding favours around your table setting, guest list and travel plans, with a clear brief for personalisation, packaging and delivery.',
    category: 'WEDDINGS', image: 'event-favours', project: 'ribbon-finished-event-favours',
    service: 'bonbonniere-custom', serviceLabel: 'Wedding bonbonniere enquiries', enquiryRoute: 'bulk',
    sections: [
      { id: 'ideas', title: 'Give the favour a place in the celebration', paragraphs: ['A sculptural keepsake can sit at each place setting, a personalised tag can finish a gift, and a boxed piece can be handed out as guests leave. Choose the role first, then discuss a design that fits it. Our photographed ribbon-finished favours show one presentation approach you can use as a reference.', 'Decide whether your priority is a reminder of the wedding, an element of the table styling or a piece guests can display at home. Share the venue colours and a reference you like, together with the dimensions available on the table. Avoid assuming that a photographed finish or box is included without checking the quote.'] },
      { id: 'guest-list', title: 'Turn the guest list into an order quantity', paragraphs: ['State whether each person, couple or household receives a favour. Count gifts for the wedding party and any extras separately, then give the total you want quoted. Bulk orders start at 10 units.', 'If a named favour also acts as a place card, send one final list that matches the seating plan. Discuss how late guest changes will be handled before approving production; additions may affect the price and schedule.'] },
      { id: 'personalisation', title: 'Keep the personal details readable', paragraphs: ['A shared name and date, a short message, or an individual guest name each creates a different preparation task. Specify the exact text and its position. The studio reviews the wording against the proposed dimensions rather than assuming a long message will fit a small piece.', 'Nominate one person to approve names, dates, colours and the presentation together. Ask what the approval stage includes and whether a physical sample or additional design work has a separate cost.'] },
      { id: 'transport', title: 'Plan packing and the journey home', paragraphs: ['Let us know if guests will travel with their favours or if the order goes directly to a venue or planner. Specify individual boxes, ribbon, tags and any assembly you expect to do yourself. Confirm the packed dimensions when luggage or table space is limited.', 'For a destination wedding, discuss the shipping destination and handling requirements before selecting a design. Delivery feasibility and timing need confirmation for the actual order.'] },
      { id: 'quote', title: 'Compare the complete order', paragraphs: ['Give a budget range and say whether it includes design, the production run, presentation and freight. Reducing the number of different versions or simplifying packaging may change the scope; ask for those options to be quoted rather than assuming a fixed price per guest.', 'Send the quantity, design reference, wording, delivery postcode, wedding date and required arrival date. Allow time for checking and setup after delivery. The studio confirms materials, finish, pricing and the production schedule after review.'] },
    ],
  },
  {
    slug: 'christening-baptism-keepsakes', title: 'Christening and baptism keepsakes: personalisation, symbols and guest favours',
    summary: 'Prepare a clear brief for christening or baptism keepsakes, from family wording and religious imagery to guest quantities and presentation.',
    category: 'CHRISTENINGS & BAPTISMS', image: 'boxed-keepsakes', project: 'personalised-boxed-keepsakes',
    service: 'bonbonniere-custom', serviceLabel: 'Religious keepsakes & bonbonniere', enquiryRoute: 'bulk',
    sections: [
      { id: 'purpose', title: 'Separate the family keepsake from guest favours', paragraphs: ['A piece kept by the family can have a different purpose from a batch given to guests. Explain who receives each version, how it will be displayed or presented and the quantity required. Bulk orders start at 10 units; discuss any separate family or godparent pieces alongside the batch.', 'For favours, decide whether one piece goes to each guest or household. Include any extras you want to retain, and identify variations that require different names or messages.'] },
      { id: 'symbols', title: 'Supply the imagery that matters to your family', paragraphs: ['If you want a cross, a religious figure or another symbol, provide a clear reference and explain the details that are important to you. Traditions and preferences vary, so the brief should identify the intended image rather than leave it to assumption.', 'Discuss whether the reference is suitable for the proposed size and production method. Only supply artwork or designs you have permission to use, and confirm the agreed interpretation at the approval stage.'] },
      { id: 'wording', title: 'Check names, dates and language together', paragraphs: ['Provide the exact spelling of the name, the ceremony date and any short message. Include accents, punctuation and the intended language. Ask how longer wording will fit before committing to a small design.', 'If the date is provisional, make that clear in the enquiry. Nominate one person to gather family feedback and approve the final wording. Changes after approval need to be reviewed for their effect on timing and cost.'] },
      { id: 'presentation', title: 'Choose the piece and its packaging together', paragraphs: ['Our boxed-keepsake gallery shows white bows, clear boxes and gold details as an example of presentation. Use the photographs to explain the style you like, then confirm the available colours, finish, dimensions and packaging for your own order.', 'Tell us whether the favours will be arranged at a reception, handed out after the ceremony or transported by a planner. Include any space constraints and say who will assemble the final presentation.'] },
      { id: 'timing', title: 'Make room for approval and delivery', paragraphs: ['Send the ceremony date and the earlier date the order needs to arrive. Include the delivery postcode and time for your own checking and setup. The studio reviews feasibility before confirming the production schedule.', 'Your enquiry should include the quantity, reference image, wording, dimensions, packaging preferences and budget scope. Mark any undecided details as questions. Materials, suitability, pricing and lead time are confirmed for the agreed brief.'] },
    ],
  },
];
export const guides: Guide[] = [
  {
    slug: 'bulk-3d-printing-quote-checklist', title: 'What to include in a bulk 3D printing quote request',
    summary: 'A practical brief helps us assess the design, quantity and delivery requirements together. Here is what to send, even without a finished 3D file.',
    category: 'PLANNING YOUR ORDER', image: 'event-favours', project: 'ribbon-finished-event-favours',
    service: 'wholesale', serviceLabel: 'Bulk & trade orders',
    sections: [
      { id: 'purpose', title: 'Start with the purpose', paragraphs: ['Describe the product and who it is for. An event keepsake, a retail item and a functional component can have very different design and packaging requirements. A reference photograph or sketch is a useful starting point; you do not need to arrive with a finished model.', 'Include approximate dimensions in millimetres and explain which measurements matter. If the piece needs to fit another object, show the connection and give the relevant dimensions rather than relying on a photograph alone.'] },
      { id: 'quantity', title: 'Separate the quantity from the variations', paragraphs: ['Our bulk orders start at 10 units. State how many pieces you need in this order, then describe any different names, colours, sizes or designs. A batch of identical pieces and a batch with individual wording require different preparation.', 'For repeat work, give the quantity per batch separately from estimated annual demand. Label an estimate as an estimate so the quote can be based on the order you are ready to discuss.'] },
      { id: 'delivery', title: 'Give the date you need delivery', paragraphs: ['Include the delivery postcode and the date the pieces need to be in your hands. For events, also give the event date. Design review, approvals, production, packaging and freight all need to fit that schedule.', 'If you have a budget range, say whether it covers design, packaging and delivery as well as the pieces themselves. Lead time, suitability and pricing are confirmed after review.'] },
      { id: 'checklist', title: 'Your enquiry checklist', paragraphs: ['Copy these points into your project brief. Unknown details can be marked “please advise”.'], points: ['Product, intended use and reference image or file', 'Approximate dimensions and any critical fit requirements', 'Quantity for this order and number of variants', 'Personalisation, preferred colour and finish', 'Individual boxes, labels or other packaging needs', 'Delivery postcode, required arrival date and event date if relevant', 'Budget range and likely repeat demand'] },
    ],
  },
  {
    slug: 'ordering-custom-event-favours', title: 'Ordering custom event favours: quantities, personalisation and packaging',
    summary: 'Plan the piece and its presentation together, from guest numbers and wording to the date your favours need to arrive.',
    category: 'EVENTS & KEEPSAKES', image: 'boxed-keepsakes', project: 'personalised-boxed-keepsakes',
    service: 'bonbonniere-custom', serviceLabel: 'Bonbonniere & keepsakes',
    sections: [
      { id: 'quantity', title: 'Decide what one favour represents', paragraphs: ['Start by deciding whether each guest, couple, household or table receives a piece. This helps turn a guest list into an order quantity. If you want extras for keepsakes or late additions, include them in the quantity you ask us to quote.', 'For planners ordering across several occasions, separate the events and their deadlines. Let us know which details stay the same and which change, such as names, dates or ribbon colours.'] },
      { id: 'personalisation', title: 'Keep a single approved wording list', paragraphs: ['Names, dates and short messages can make a keepsake specific to an occasion. Send the exact spelling, capitalisation and punctuation you want, and identify where the wording should appear. We review whether the text suits the size and design.', 'If several people are involved in approval, nominate one person to send the final consolidated feedback. Discuss the approval format and any sample costs before production. Changes to approved wording may affect the scope and schedule.'] },
      { id: 'packaging', title: 'Plan the whole presentation', paragraphs: ['The boxed keepsakes in our gallery show clear presentation boxes, white bows and gold details. Use these as a visual reference when describing the look you want; the available combination is confirmed for your order.', 'Ask whether you need individual presentation boxes, personalised tags, ribbon, or protective packing for transport. Describe the finished arrangement you expect to receive, including any assembly you intend to handle yourself.'] },
      { id: 'timing', title: 'Work back from arrival, not the event', paragraphs: ['Give both the event date and the date you need the favours delivered. Include time for your own checking, assembly and table setup. We assess the production and shipping requirements before confirming a timeframe.', 'Bulk enquiries start at 10 units. To begin, send your estimated quantity, a reference you like, the required wording, packaging preferences and delivery postcode.'] },
    ],
  },
  {
    slug: 'what-affects-bulk-3d-printing-cost', title: 'What affects the cost of a custom 3D printed batch?',
    summary: 'Quantity is only one part of a quote. Design preparation, size, finish, variants and packaging also shape the scope of your order.',
    category: 'UNDERSTANDING YOUR QUOTE', image: 'gift-boxes', project: 'personalised-gift-boxes',
    service: 'wholesale', serviceLabel: 'Discuss a bulk quote',
    sections: [
      { id: 'design', title: 'The starting design matters', paragraphs: ['A ready-to-review model and a new design developed from a sketch involve different work. Tell us what you already have and what still needs to be designed or personalised. File review may identify changes needed before production.', 'Ask the quote to distinguish design or setup work from the production run. If you expect to reorder, also ask which parts of the scope would need to be reviewed again when the design or wording changes.'] },
      { id: 'size', title: 'Size and detail affect the production brief', paragraphs: ['Dimensions, geometry, material and the required finish influence how a piece can be produced. A price for a small version should not be treated as a fixed guide for a larger one.', 'Explain which features are essential and where you have flexibility. Material and finish options are confirmed for the intended use; a decorative example does not establish suitability for a functional part.'] },
      { id: 'variants', title: 'Count the versions as well as the pieces', paragraphs: ['Ten identical pieces and ten individually named pieces are different briefs. Share the number of designs, colours and wording variations so the preparation can be considered alongside the quantity.', 'The gift boxes in our gallery illustrate variations in colour, ribbon and message plaques. When asking about a similar order, specify the combination you want rather than assuming every photographed detail is included.'] },
      { id: 'compare', title: 'Compare the complete scope', paragraphs: ['Check what each quote includes before comparing its total. A useful comparison covers the same product specification and delivery requirements.'], points: ['Design preparation and agreed revisions', 'Quantity, dimensions, material and finish', 'Personalisation and number of variants', 'Any sample or approval stage', 'Presentation packaging and assembly', 'Freight, applicable tax and required delivery date'] },
      { id: 'request', title: 'Ask for a quote around your priorities', paragraphs: ['Send your budget range along with the quantity and intended use. Say whether the budget includes packaging and freight. We will review feasibility and confirm pricing for the agreed scope; there is no universal per-piece rate for every custom design.'] },
    ],
  },
  {
    slug: 'planning-repeat-production-orders', title: 'Planning repeat orders for your business or organisation',
    summary: 'A repeat order starts with a clear specification. Separate the first batch, your forecast and the details that need to stay consistent.',
    category: 'ONGOING SUPPLY', image: 'commemorative-icons', project: 'commemorative-religious-icons',
    service: 'ongoing-supply', serviceLabel: 'Discuss ongoing supply', enquiryRoute: 'supply',
    sections: [
      { id: 'forecast', title: 'Separate the first order from the forecast', paragraphs: ['Tell us what you need first: quantity, destination and required delivery date. Then outline your expected ordering frequency and annual demand. This gives us a basis for discussing future batches without treating a forecast as a confirmed order.', 'If demand changes around events or seasons, describe those peaks. Include whether deliveries go to one location or several. Capacity, timing and the arrangement itself need to be agreed before a recurring commitment.'] },
      { id: 'specification', title: 'Agree what should stay the same', paragraphs: ['A repeatable brief records more than the product name. Identify the approved design version, dimensions, wording, colour, finish and packaging. For a functional item, include the fit or performance requirements that need to be assessed.', 'Discuss whether an approval sample is appropriate, what it would cost and what you will use it to check. Any acceptance criteria and checks need to be agreed for the actual product.'], points: ['Design version and approved personalisation', 'Dimensions and any critical requirements', 'Material, colour and finish', 'Packaging, labels and delivery arrangement', 'Who approves the batch and handles changes'] },
      { id: 'changes', title: 'Give changes their own review', paragraphs: ['A new name, revised logo, different material or new size may change the work involved. Send a clear revision list before requesting the next run, rather than assuming a previous quote covers an altered design.', 'Keep the approved reference and revised brief together so everyone can identify what changed. Ask for the impact on price and delivery to be confirmed before proceeding.'] },
      { id: 'arrangement', title: 'Bring purchasing requirements into the conversation', paragraphs: ['If your organisation uses purchase orders, supplier onboarding or confidentiality requirements, mention them at enquiry stage. We can review the requirements alongside the production brief.', 'Our ongoing-supply page is an invitation to discuss an arrangement. Pricing, delivery commitments, quality acceptance and other terms remain subject to review and mutual agreement. Start with your first-batch requirements and a realistic forecast.'] },
    ],
  },
  ...occasionGuides,
];
export const getGuide = (slug: string) => guides.find(guide => guide.slug === slug);

