export const policies = [
  { slug: 'privacy-policy', title: 'Privacy notice', intro: 'This notice explains how Impeccable Sculptures handles information provided through our enquiry website.', sections: [
    { title: 'Information you provide', text: 'We collect the contact details, company information, project brief, quantities, delivery requirements and supporting files you choose to submit. Optional fields can be left blank. Do not include information about other people unless you have permission, or confidential material that needs a separate agreement before disclosure.' },
    { title: 'How we use it', text: 'We use your information to assess the project, prepare a quote, respond to you and manage any resulting order. Submitting an enquiry does not subscribe you to marketing. We may retain correspondence and order records needed to service your project and meet applicable record-keeping requirements.' },
    { title: 'Storage and service providers', text: 'The website uses Cloudflare hosting, private file storage and spam verification. Where online submissions are enabled, Resend processes enquiry notifications and confirmation emails. These providers may process information outside Australia. File links in studio notifications expire; uploaded files are not published in a public gallery.' },
    { title: 'Website and enquiry data', text: 'Hosting and spam-protection services may process technical connection information such as IP addresses. The enquiry records the page path, referring website hostname and campaign tags, where available, to help us understand how enquiries reach us. We do not put your project brief or contact information into advertising events.' },
    { title: 'Access, correction and questions', text: 'Email info@isculptures.com.au to ask about your information, request access or correction, request deletion of files no longer needed, or raise a privacy concern. Include your enquiry reference if available. We may need to verify your identity and review any record-keeping obligations before acting.' }
  ] },
  { slug: 'terms-of-service', title: 'Enquiries & custom orders', intro: 'The website is an enquiry service. Submitting a brief is a request for review and a quote; it does not place an order, reserve capacity or confirm a delivery date.', sections: [
    { title: 'Quotes and approval', text: 'We confirm feasibility, scope, quantities, materials, finish, pricing, any design or sample costs, delivery and payment arrangements in writing. An order proceeds only once the relevant quote and approval requirements are agreed.' },
    { title: 'Your designs and files', text: 'Only provide designs, logos, images and files you own or have permission to use for the requested work. Raise confidentiality, licensing and design-ownership requirements before sharing restricted material or commissioning design work.' },
    { title: 'Production and changes', text: 'Please check names, dates, dimensions and specifications carefully at approval. Changes after approval may affect cost and timing and need to be agreed before they are made. Samples and acceptance criteria should be discussed where fit, finish or repeatability are important.' },
    { title: 'Repeat supply', text: 'Repeat orders and supply arrangements are subject to agreed specifications, capacity and written commercial terms. Forecast demand is distinguished from confirmed purchase quantities. Enquiring about a contract does not create a supply commitment.' },
    { title: 'Questions or problems', text: 'Contact info@isculptures.com.au with your enquiry or order reference. These website notes do not exclude rights or remedies that cannot be excluded under applicable Australian law. Individual purchases through Etsy are also subject to the terms applicable to that transaction.' }
  ] },
  { slug: 'shipping-policy', title: 'Delivery information', intro: 'We offer Australia-wide delivery. Shipping arrangements are confirmed as part of the quote for your custom order.', sections: [
    { title: 'Timing', text: 'Provide the date you need the items delivered and say whether it is fixed. Production, approval and freight time are considered together before a timeline is confirmed. An enquiry alone does not guarantee delivery by a requested date.' },
    { title: 'Packaging and destinations', text: 'Include your suburb or postcode, packaging requirements and any need to send to several locations. Freight and packaging charges depend on the order and destination and will be confirmed with you.' },
    { title: 'Delivery issues', text: 'If an order arrives damaged or does not arrive as expected, contact info@isculptures.com.au with your order reference and relevant photographs or delivery information so we can investigate.' }
  ] },
  { slug: 'refund-policy', title: 'Order issues & changes', intro: 'If something is wrong with your order, please contact the studio so we can review it with you.', sections: [
    { title: 'Help us assess the issue', text: 'Email info@isculptures.com.au with your order reference, a description of the concern and photographs where useful. Keep the items and packaging while we assess any production or delivery issue.' },
    { title: 'Changes and cancellation requests', text: 'Contact us as soon as possible if you need to change or cancel custom work. The options depend on the agreed terms and whether design, materials or production work has begun. Any costs or revised timing must be discussed for the order.' },
    { title: 'Your rights', text: 'These notes do not exclude rights or remedies that cannot be excluded under applicable Australian law. For an Etsy purchase, you can also contact us through the order conversation on Etsy.' }
  ] }
];
