export type Service = { slug: string; title: string; description: string; eyebrow: string; intro: string; sections: { title: string; text: string; points?: string[] }[]; cta: string; route?: string };
export const services: Service[] = [
  { slug: 'wholesale', title: 'Wholesale & Bulk 3D Printing Australia', description: 'Custom products in quantities from 10 units for retailers, parishes, event planners and businesses. Sydney production and Australia-wide delivery.', eyebrow: 'BULK & BUSINESS', intro: 'Custom products, ordered by the batch. We work with retailers, churches, event organisers and businesses to turn an idea into a practical production brief.', sections: [
    { title: 'Start with 10 units', text: 'Bulk orders start at 10 units. Tell us the quantity per batch and whether you expect to reorder. Price depends on the size, material, design work and finish—not quantity alone.' },
    { title: 'Made for your customers or community', text: 'Discuss religious keepsakes, bonbonniere, branded gifts and custom products. Include how the pieces will be used or sold so we can assess the right approach.', points: ['Retailers and resellers', 'Parishes, churches and community organisations', 'Event planners, venues and agencies', 'Businesses buying branded products'] },
    { title: 'What your quote needs', text: 'Send an approximate size, reference, quantity, destination and required delivery date. Let us know about individual personalisation, packaging or different variants. Minimums, design costs, freight and lead time are confirmed with your quote.' }
  ], cta: 'Request a bulk quote', route: 'supply' },
  { slug: 'events-custom-gifts', title: 'Custom Corporate Gifts & Event Favours Australia', description: 'Enquire about branded gifts, personalised event favours and corporate keepsakes from 10 units. Designed around your event brief and delivery needs.', eyebrow: 'CORPORATE GIFTS & EVENTS', intro: 'Give your event something of its own. Discuss branded keepsakes, personalised gifts and event favours produced as a coordinated run.', sections: [
    { title: 'Plan around the delivery date', text: 'Tell us when you need the items in hand, along with the event date. Design approval, production, finishing and shipping all need to fit the schedule. We confirm feasibility before accepting the order.' },
    { title: 'Branding and individual details', text: 'Share your logo, wording, colours and approximate dimensions. For names or multiple versions, include the number of variants so these can be considered in the quote.' },
    { title: 'For planners and repeat events', text: 'If you organise events for clients or run an annual program, include your expected repeat demand. We can discuss a sample or approval stage, batch planning and packaging requirements.' }
  ], cta: 'Enquire about an event run', route: 'bulk' },
  { slug: 'bonbonniere-custom', title: 'Custom Bonbonniere & Religious Keepsakes Australia', description: 'Personalised bonbonniere, wedding and christening favours, and religious keepsakes. Bulk enquiries from 10 units with Australia-wide delivery.', eyebrow: 'OCCASIONS & COMMUNITY', intro: 'Personalised keepsakes for weddings, christenings, baptisms and parish occasions. Bring the meaning, the names and the date; we’ll review how to make the pieces.', sections: [
    { title: 'A set that belongs to your occasion', text: 'Discuss statues, religious keepsakes and custom favours, with personalisation such as names, dates or text where suitable for the design.' },
    { title: 'For families, planners and parishes', text: 'Orders start at 10 units. Share your guest count or community quantity, approximate size and preferred finish. We confirm materials and design options after reviewing the brief.' },
    { title: 'Allow time for the details', text: 'Confirm spelling, dates and the approved design before production. Tell us about packaging and your required delivery date when you enquire. For individual ready-made pieces, visit our Etsy shop.' }
  ], cta: 'Plan your keepsake order', route: 'bulk' },
  { slug: 'industrial', title: 'Custom 3D Printed Parts & Prototypes Sydney', description: 'Discuss custom prototypes, jigs, fixtures and repeat batches of 3D printed parts. Material and production suitability reviewed against your intended use.', eyebrow: 'PARTS & PROTOTYPES', intro: 'A functional part starts with understanding what it needs to do. Send a model or drawing and the operating requirements so we can review suitability for 3D printing.', sections: [
    { title: 'Tell us about the application', text: 'Include dimensions, fit, loads, temperature, exposure and any tolerances that matter. A photograph alone may not establish the dimensions or performance needed.' },
    { title: 'Prototype before committing to a run', text: 'Discuss a first sample or prototype to check fit and function. Any testing, acceptance criteria and changes should be agreed before repeat production.' },
    { title: 'Materials are selected for the brief', text: 'Material, orientation, finish and manufacturing method affect performance. We confirm what we can supply after review. Include any testing or certification requirements so we can assess whether the project is suitable.' }
  ], cta: 'Discuss a part or prototype', route: 'file' },
  { slug: 'ongoing-supply', title: 'Repeat Orders & Ongoing 3D Printing Supply', description: 'Discuss recurring batches, wholesale supply and custom production arrangements. Share quantities, annual demand and delivery schedules with our Sydney studio.', eyebrow: 'REPEAT ORDERS & SUPPLY', intro: 'Make the next order part of the conversation from the start. We welcome enquiries about recurring batches and longer-term supply arrangements.', sections: [
    { title: 'Forecast the work', text: 'Tell us your expected quantity per batch, annual demand, ordering frequency and first delivery date. Estimates are welcome; distinguish them from quantities you are ready to commit to.' },
    { title: 'Agree a repeatable specification', text: 'Discuss the design version, material, finish, colour, packaging and approval sample. Changes between runs should be reviewed before a new batch is confirmed.' },
    { title: 'Put the arrangement in writing', text: 'Pricing, lead times, payment, delivery, quality acceptance and changes need to be agreed for the arrangement. Purchase orders, confidentiality requirements and supplier onboarding can be raised during the enquiry.' },
    { title: 'Start with a suitable first run', text: 'A first order can establish the specification and practical production requirements before a longer-term commitment. Supply agreements remain subject to capacity and mutual agreement.' }
  ], cta: 'Discuss ongoing supply', route: 'supply' },
  { slug: 'about', title: 'About Impeccable Sculptures | Sydney Studio', description: 'Impeccable Sculptures is a Sydney studio for custom 3D printing, event keepsakes and bulk enquiries. Contact the studio directly to discuss your project.', eyebrow: 'THE SYDNEY STUDIO', intro: 'Impeccable Sculptures is a Sydney-based studio working with custom 3D printed products, personalised keepsakes and event orders.', sections: [
    { title: 'From the occasion to the object', text: 'Our offering includes religious keepsakes, bonbonniere, custom gifts and enquiries for business production. We discuss the design, quantity and finish with you before confirming the scope.' },
    { title: 'A direct conversation', text: 'Contact the studio at info@isculptures.com.au or 0437 383 684. For a useful quote, include what you are making, the quantity and when you need delivery.' },
    { title: 'Buying an individual piece?', text: 'Our enquiry site focuses on custom projects and bulk orders from 10 units. Individual pieces are available through our Etsy shop.' }
  ], cta: 'Contact the studio' }
];
