export type Service = { slug: string; title: string; description: string; eyebrow: string; intro: string; sections: { title: string; text: string; points?: string[] }[]; cta: string; route?: string;
  /** Visible H1 when the search title is kept short enough to show in full. */
  heading?: string;
  /** Short, confirmed facts for the page's quick-facts panel. */
  facts?: { label: string; value: string; href?: string }[];
  /** Project slugs and testimonial ids, in display order. */
  work?: string[]; reviews?: string[] };
export const services: Service[] = [
  { slug: 'wholesale', title: 'Wholesale & bulk 3D printing', heading: 'Wholesale & bulk 3D printing in Australia', description: 'Bulk 3D printing for shops, parishes, event planners and businesses. Orders start at 10 units, printed in Sydney and delivered Australia-wide.', eyebrow: 'BULK & TRADE', intro: 'We print custom products in batches for shops, churches, event organisers and businesses. Send us your idea and we’ll help turn it into something we can quote and make.', sections: [
    { title: 'Orders start at 10 units', text: 'Our minimum is 10 units per batch. Let us know how many you need now and whether you’re likely to reorder. Quantity isn’t the only thing that sets the price: size, material, design work and finish all play a part.' },
    { title: 'Who we print for', text: 'We make religious keepsakes, bonbonniere, branded gifts and other custom products. Tell us how the pieces will be used or sold, because that changes how we approach the design and packaging.', points: ['Retailers and resellers', 'Parishes, churches and community groups', 'Event planners, venues and agencies', 'Businesses ordering branded products'] },
    { title: 'What to include in your enquiry', text: 'Send a rough size, a reference photo or file, the quantity, where it’s going and when you need it. Mention any personalisation, packaging or different versions. We’ll confirm minimums, design costs, freight and lead time in your quote.' }
  ], cta: 'Request a bulk quote', route: 'supply',
  facts: [{ label: 'Minimum', value: '10 units per batch' }, { label: 'Price depends on', value: 'Size, material, design work and finish' }, { label: 'Delivery', value: 'Australia-wide from Sydney' }, { label: 'In your quote', value: 'Design costs, freight and lead time' }],
  work: ['personalised-rose-sculptures', 'commemorative-religious-icons', 'personalised-gift-boxes'], reviews: ['judgeme-elias-el-tarraf', 'judgeme-nicole-s', 'google-anthony-ngo'] },
  { slug: 'events-custom-gifts', title: 'Corporate gifts & event favours', heading: 'Custom corporate gifts & event favours', description: 'Branded corporate gifts, personalised event favours and keepsakes, made in batches from 10 units. Tell us your event date and we’ll plan the order around it.', eyebrow: 'CORPORATE GIFTS & EVENTS', intro: 'Branded gifts for clients and staff, and personalised favours for your guests, made as one matching batch.', sections: [
    { title: 'Start with your delivery date', text: 'Tell us the date of your event and when you need the items in hand. Design approval, printing, finishing and shipping all have to fit before then, so we check the timeline works before we accept the order.' },
    { title: 'Logos, names and wording', text: 'Send your logo, wording, brand colours and a rough size. If each piece carries a different name, or there are several versions, tell us how many so we can price it properly.' },
    { title: 'Event planners and annual events', text: 'If you plan events for clients or run the same event every year, give us an idea of how many you’ll need each time. We can talk about a sample, approval steps, batch timing and packaging.' }
  ], cta: 'Enquire about an event order', route: 'bulk',
  facts: [{ label: 'Minimum', value: '10 units per order' }, { label: 'Personalisation', value: 'Logos, names, wording and colours' }, { label: 'Timing', value: 'Planned around your event date' }, { label: 'Delivery', value: 'Australia-wide' }],
  work: ['personalised-gift-boxes', 'personalised-favour-tags', 'ribbon-finished-event-favours'], reviews: ['google-fadia-awad', 'judgeme-anika-dahdah', 'judgeme-nicole-s'] },
  { slug: 'bonbonniere-custom', title: 'Bonbonniere & religious keepsakes', heading: 'Custom bonbonniere & religious keepsakes', description: 'Personalised bonbonniere and religious keepsakes for weddings, christenings, baptisms and parish events. Orders from 10 units, delivered anywhere in Australia.', eyebrow: 'BONBONNIERE & KEEPSAKES', intro: 'Personalised favours and religious keepsakes for weddings, christenings, baptisms and parish events. Send us the names, the date and what the occasion means to you, and we’ll work out how to make it.', sections: [
    { title: 'Made for your occasion', text: 'We make statues, religious keepsakes and custom favours. Names, dates or a short message can be added where the design has room for them.' },
    { title: 'For families, planners and parishes', text: 'Orders start at 10 units. Tell us your guest numbers, roughly how big you’d like each piece and the finish you have in mind. We’ll suggest materials and design options once we’ve seen your brief.' },
    { title: 'Leave time to check the details', text: 'You check and approve every name, date and the final design before we print. Tell us about packaging and your delivery date when you enquire. Looking for a single ready-made piece? Visit our Etsy shop.' }
  ], cta: 'Plan your keepsake order', route: 'bulk',
  facts: [{ label: 'Minimum', value: '10 units' }, { label: 'Occasions', value: 'Weddings, christenings, baptisms and parish events' }, { label: 'Personalisation', value: 'Names, dates or a short message' }, { label: 'Single pieces', value: 'Our Etsy shop', href: 'https://www.etsy.com/au/shop/iSculptures' }],
  work: ['ribbon-finished-event-favours', 'personalised-boxed-keepsakes', 'commemorative-religious-icons'], reviews: ['google-fadia-awad', 'google-john', 'judgeme-anthony-j'] },
  { slug: 'industrial', title: '3D printed parts & prototypes Sydney', heading: '3D printed parts & prototypes in Sydney', description: 'Prototypes, jigs, fixtures and repeat batches of 3D printed parts. Send us your model or drawing and tell us what the part needs to do.', eyebrow: 'PARTS & PROTOTYPES', intro: 'For a working part, we need to know what it has to do. Send us a model or drawing along with how it’ll be used, and we’ll tell you whether 3D printing is a good fit.', sections: [
    { title: 'Tell us how the part is used', text: 'Include dimensions, what it fits with, loads, heat, outdoor exposure and any tolerances that matter. A photo on its own usually isn’t enough to get the measurements or performance right.' },
    { title: 'Prototype first, then a production run', text: 'Start with a sample or prototype to check fit and function. Agree any testing, acceptance criteria and changes before we print a larger batch.' },
    { title: 'Choosing the material', text: 'Material, print orientation, finish and method all affect how a part performs. We’ll tell you what we can supply once we’ve reviewed the brief. If the part needs testing or certification, mention it up front so we can tell you whether the job suits us.' }
  ], cta: 'Ask about a part or prototype', route: 'file',
  facts: [{ label: 'Send us', value: 'A model or drawing, and how the part is used' }, { label: 'Files', value: 'STL, OBJ, 3MF, PDF or photos' }, { label: 'First step', value: 'A prototype to check fit and function' }, { label: 'Materials', value: 'Recommended once we’ve seen the brief' }],
  reviews: ['google-hydrion-admin', 'google-david-bui'] },
  { slug: 'ongoing-supply', title: 'Repeat 3D printing & ongoing supply', heading: 'Repeat orders & ongoing 3D printing supply', description: 'Ongoing 3D printing supply for businesses that reorder. Share your batch sizes, yearly demand and delivery schedule with our Sydney studio.', eyebrow: 'REPEAT ORDERS & SUPPLY', intro: 'If you’ll need the same product more than once, tell us at the start. We’re happy to talk about regular batches and longer-term supply.', sections: [
    { title: 'Give us a forecast', text: 'Let us know how many you need per batch, your rough yearly demand, how often you’ll order and when the first delivery is due. Estimates are fine; just tell us which numbers are firm.' },
    { title: 'Lock in the specification', text: 'Agree the design version, material, finish, colour, packaging and an approval sample. Any changes between batches get checked before the next one is confirmed.' },
    { title: 'Put the arrangement in writing', text: 'Price, lead times, payment, delivery, quality checks and how changes are handled all need to be agreed in writing. You can raise purchase orders, confidentiality and supplier onboarding when you enquire.' },
    { title: 'Start with a first order', text: 'A first batch is a good way to settle the specification and sort out practical details before anyone commits long term. Supply agreements depend on our capacity and need to work for both of us.' }
  ], cta: 'Talk to us about supply', route: 'supply',
  facts: [{ label: 'Tell us', value: 'Batch size and yearly demand' }, { label: 'Specification', value: 'Design, material, finish and packaging' }, { label: 'Arrangement', value: 'Price, lead times and delivery, in writing' }, { label: 'Delivery', value: 'Australia-wide' }],
  work: ['personalised-rose-sculptures', 'ribbon-finished-event-favours', 'custom-sculptures-keepsakes'], reviews: ['google-hydrion-admin', 'judgeme-nicole-s', 'judgeme-elias-el-tarraf'] },
  { slug: 'about', title: 'About Impeccable Sculptures, a Sydney 3D printing studio', description: 'Impeccable Sculptures is a Sydney studio that 3D prints custom keepsakes, event favours, gifts and parts. Email or call us to talk about your project.', eyebrow: 'ABOUT US', intro: 'We’re a Sydney studio making custom 3D printed keepsakes, event favours, gifts and orders for businesses.', sections: [
    { title: 'What we make', text: 'Religious keepsakes, bonbonniere, custom gifts and production runs for businesses. Before we confirm anything, we go through the design, quantity and finish with you.' },
    { title: 'Talk to us directly', text: 'Email info@isculptures.com.au or call 0437 383 684. For a useful quote, tell us what you’re making, how many you need and when you need them.' },
    { title: 'After a single piece?', text: 'This site is for custom projects and bulk orders of 10 or more. You can buy individual pieces from our Etsy shop.' }
  ], cta: 'Get in touch', heading: 'About Impeccable Sculptures',
  facts: [{ label: 'Studio', value: 'Sydney, Australia' }, { label: 'Email', value: 'info@isculptures.com.au', href: 'mailto:info@isculptures.com.au' }, { label: 'Phone', value: '0437 383 684', href: 'tel:+61437383684' }, { label: 'Custom & bulk', value: 'From 10 units' }],
  work: ['custom-sculptures-keepsakes', 'commemorative-religious-icons', 'personalised-boxed-keepsakes'], reviews: ['judgeme-elias-el-tarraf', 'google-fadia-awad', 'google-hydrion-admin'] }
];
