import type { Testimonial } from './types';
// Published reviews supplied by the studio owner on 11 September 2026.
export const testimonials: Testimonial[] = [
  { id: 'judgeme-anika-dahdah', quote: 'So happy with my purchase - it made for a lovely gift this Christmas. Very helpful and prompt delivery. Will definitely recommend', author: 'Anika Dahdah', role: 'Saint Charbel “Revered” Statue customer', source: 'judgeme', rating: 5 },
  { id: 'judgeme-sheena-pal', quote: 'The description and photo matches the product. I love my Angel Michael sculpture :)', author: 'Sheena Pal', role: 'Saint Michael “Defeats Beast” Statue customer', source: 'judgeme', rating: 5 },
  { id: 'judgeme-elias-el-tarraf', quote: 'This sculpture exceeded my expectations. Daniel was a pleasure to deal with and he checked in to ensure I was happy with the product. Would absolutely recommend to my family and friends. Thanks again!', author: 'Elias El-tarraf', role: 'Saint Michael “Defeats Beast” Statue customer', source: 'judgeme', rating: 5, featured: true },
  { id: 'judgeme-anthony-j', quote: 'Beautifully crafted with incredible detail! This sculpture adds a serene and spiritual presence to my home. Highly recommend!', author: 'Anthony J', role: 'Jesus Christ “Sacred Heart” Statue customer', source: 'judgeme', rating: 5 },
  { id: 'judgeme-nicole-s', quote: 'Loved the product! Such great quality and the perfect gift idea and keepsake for home. Would be purchasing again. Very easy process and great communication with staff', author: 'Nicole S', role: 'Jesus Christ “Sacred Heart” Statue customer', source: 'judgeme', rating: 5 },
  { id: 'etsy-vojislav-2026-07-30', quote: "the Saint Michael The Archangel statue silk gold looks epic love its design and detail and powerful presence it was great buying from your store again your one of the top best sellers I've bought from a highly recommended seller I'm very satisfied with the statues that I've bought from your store and thank you for the extra gift", author: 'Vojislav', role: 'Saint Michael the Archangel statue customer', source: 'etsy', rating: 5, date: '2026-07-30', featured: true },
  { id: 'etsy-estelle-2026-03-03', quote: 'Great piece love it !', author: 'Estelle', role: 'Saint George the Victorious icon customer', source: 'etsy', rating: 5, date: '2026-03-03' },
  { id: 'etsy-vojislav-2025-10-07', quote: "The SAINT MICHAEL THE ARCHANGEL bronze statue looks awesome love it's design and detail and it's holy power looks great with my other statues MICHAEL THE ARCHANGEL is GODS champion your one of the top best sellers I've bought from on ETSY it was great buying from you again Cheers for the keychains of SAINT MICHAEL THE ARCHANGEL that came with the statue much appreciated", author: 'Vojislav', role: 'Saint Michael the Archangel statue customer', source: 'etsy', rating: 5, date: '2025-10-07' },
  { id: 'etsy-vojislav-2025-08-22', quote: "The statue of SAINT MICHAEL THE ARCHANGEL looks awesome it's one of the top best statues I've bought love it's design and detail Your one of the top best sellers I've bought from on ETSY was great buying from you again", author: 'Vojislav', role: 'Saint Michael the Archangel statue customer', source: 'etsy', rating: 5, date: '2025-08-22' },
  { id: 'etsy-klaus-2025-08-07', quote: 'everything is fine, thank you', author: 'Klaus', role: 'Saint Michael the Archangel statue customer', source: 'etsy', rating: 5, date: '2025-08-07' },
  { id: 'google-david-bui', quote: 'Ordered a 3D model for a hard drive and it turned out awesome! Highly recommend', author: 'David Bui', role: 'Custom hard-drive model customer', source: 'google', rating: 5 },
  { id: 'google-anthony-ngo', quote: 'Amazing details and work of art. Very pleased with the products.', author: 'Anthony Ngo', role: 'Custom sculpture customer', source: 'google', rating: 5 },
  { id: 'google-fadia-awad', quote: 'Thankyou impeccable sculptures for taking the time to create my baby favours and coasters for my daughters special day, your work is truly amazing and detailed, would highly recommended to everyone', author: 'Fadia Awad', role: 'Baby favours and coasters customer', source: 'google', rating: 5, featured: true },
  { id: 'google-john', quote: 'Ordered this beautifully designed St Rita sculpture. Arrived on time and finished in a beautiful rose beige colour. Highly recommend for all occasions.', author: 'John', role: 'St Rita sculpture customer', source: 'google', rating: 5 },
  { id: 'google-hydrion-admin', quote: 'Had 3D printing for prototyping made. Very pleased with service & result. High quality, prompt, professional. Definitely recommend.', author: 'Hydrion Admin', role: '3D printing prototype customer', source: 'google', rating: 5 },
];
export const featuredTestimonials = () => testimonials.filter(t => t.featured);
export const testimonialsFor = (slug: string) => testimonials.filter(t => t.projectSlug === slug);
