import PrinterBackdrop from './components/printer-backdrop';
import WorkGrid from './components/work-grid';
import { featuredProjects } from '../content/projects';

export default function Home() {
  return <main id="main-content">
    <PrinterBackdrop/>
    <section className="hero" id="top">
      <div className="eyebrow">SYDNEY STUDIO · AUSTRALIA-WIDE DELIVERY</div>
      <h1 className="business-heading">Made for<br/><i>more than one.</i></h1>
      <p className="hero-service">Custom 3D printing for bulk orders &amp; business.</p>
      <p>Event favours, branded gifts and custom products for planners, businesses, retailers and parishes. Bulk orders from 10 units, with repeat supply enquiries welcome.</p>
      <div className="actions"><a className="primary" href="/enquiry">Request a bulk quote <span>↗</span></a><a className="secondary" href="/enquiry?route=supply">Discuss ongoing supply</a></div>
      <div className="scroll-note">FROM AN IDEA TO A PRODUCTION RUN ↓</div>
    </section>
    <section className="case light" id="b2b"><p className="section-tag">01 / BULK &amp; BUSINESS</p><h2>Your next batch.<br/>Your next <i>supplier.</i></h2><div className="b2b-copy"><p>Tell us what you need, how many, and when. We’ll review the design and production requirements before confirming a quote.</p><ul className="b2b-points"><li>Bulk orders from 10 units</li><li>Custom designs and personalisation</li><li>One-off batches and repeat-order enquiries</li><li>Direct contact with the Sydney studio</li></ul><a className="primary" href="/pages/wholesale">Explore bulk &amp; trade <span>↗</span></a></div></section>
    <section className="content-section selected-work" id="work"><p className="section-tag">FROM THE STUDIO</p><h2>Made, personalised<br/>&amp; ready to give.</h2><p className="portfolio-intro">A closer look at our event favours, commemorative pieces and custom gift boxes.</p><WorkGrid items={featuredProjects()}/><div className="portfolio-actions"><a className="secondary" href="/work">Explore selected work ↗</a><a href="https://www.instagram.com/impeccablesculptures/" target="_blank" rel="noreferrer">Latest work on Instagram ↗</a></div></section>
    <section className="case" id="events"><p className="section-tag">02 / EVENTS &amp; OCCASIONS</p><h2>Many pieces.<br/>One <i>occasion.</i></h2><div className="case-copy"><p>Bonbonniere, wedding and christening favours, religious keepsakes and branded event gifts. Share your quantity, personalisation and delivery date so we can assess the complete run.</p><a href="/pages/events-custom-gifts">Corporate gifts &amp; events →</a><br/><a href="/pages/bonbonniere-custom">Bonbonniere &amp; keepsakes →</a></div></section>
    <section className="case" id="supply"><p className="section-tag">03 / ONGOING SUPPLY</p><h2>Plan beyond<br/>the first <i>order.</i></h2><div className="case-copy"><p>Ordering for clients, a store or an organisation? Discuss repeat batches, estimated annual demand, packaging and scheduled deliveries with us.</p><a href="/pages/ongoing-supply">Discuss a supply arrangement →</a></div></section>
    <section className="case" id="printing"><p className="section-tag">04 / CAPABILITIES</p><h2>Make it fit<br/>the <i>purpose.</i></h2><div className="case-copy"><p>Start with a sketch, reference image or 3D file. We review material, size, finish and intended use—including enquiries for prototypes, jigs and functional parts.</p><a href="/pages/industrial">Custom parts &amp; prototypes →</a></div></section>
    <section className="content-section" id="process"><p className="section-tag">05 / HOW IT WORKS</p><h2>A clear path to production.</h2><ol className="process-grid"><li><b>01 / Share the brief</b><p>Tell us the use, quantity, budget and delivery requirements. You don’t need a finished design.</p></li><li><b>02 / Agree the details</b><p>We review feasibility and confirm scope, pricing, lead time and any design or sample costs.</p></li><li><b>03 / Approve &amp; produce</b><p>Agree the specification and approval steps before production. Delivery and repeat orders are planned with you.</p></li></ol></section>
    <section className="content-section" id="faq"><p className="section-tag">06 / BEFORE YOU ENQUIRE</p><h2>A few useful answers.</h2><div className="faq-list"><details><summary>What is the minimum order?</summary><p>Bulk orders start at 10 units. Pricing depends on the product, size, finish and design work involved. Send your expected quantity and we’ll confirm a quote.</p></details><details><summary>Can you work to an event deadline?</summary><p>Tell us the date you need delivery, not just the event date. We’ll review capacity, approvals and shipping before confirming a timeframe.</p></details><details><summary>Can I order the same design again?</summary><p>You can enquire about repeat orders or ongoing supply. Include your likely quantity per batch and expected annual demand so we can discuss an arrangement.</p></details><details><summary>Do I need a 3D file?</summary><p>No. A description, dimensions and reference images are a useful starting point. Any design work and approval stages will be included in the quote.</p></details><details><summary>Do you deliver across Australia?</summary><p>Australia-wide delivery is available. Freight, packaging and delivery timing are confirmed for your order and destination.</p></details></div></section>
  </main>;
}
