import PrinterBackdrop from './components/printer-backdrop';
import GuideGrid from './components/guide-grid';
import MockupNote from './components/mockup-note';
import { guides } from '../content/guides';
import { featuredTestimonials } from '../content/testimonials';
import { SOURCE_LABELS } from '../content/types';
import media from '../content/work-media.json';
import { CONTACT, SITE_URL } from '../lib/site';

const gallery = [
  { key: 'custom-sculptures', slug: 'custom-sculptures-keepsakes', title: 'Gold character sculptures', label: 'CUSTOM SCULPTURES' },
  { key: 'event-favours', slug: 'ribbon-finished-event-favours', title: 'Boxed favours with ribbon', label: 'EVENT FAVOURS' },
  { key: 'yellow-rose-sculptures', slug: 'personalised-rose-sculptures', title: 'Personalised yellow roses', label: 'PERSONALISED KEEPSAKES' },
] as const;
function Chapter({ number, label }: { number: string; label: string }) { return <div className="chapter-marker"><span>{number}</span><span>{label}</span></div>; }

export default function Home() {
  const reviews = featuredTestimonials();
  const website = { '@context': 'https://schema.org', '@type': 'WebSite', '@id': SITE_URL + '/#website', url: SITE_URL + '/', name: CONTACT.name, alternateName: 'iSculptures', inLanguage: 'en-AU', publisher: { '@id': SITE_URL + '/#organisation' } };
  // Headings keep a space before each <br/> so crawlers don't read the lines as one word.
  return <main id="main-content" className="cinematic-home sculpture-story">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(website).replace(/</g, '\\u003c') }}/>
    <PrinterBackdrop/>
    <section className="hero cinema-hero" id="top">
      <div className="eyebrow">CUSTOM &amp; BULK 3D PRINTING / SYDNEY STUDIO</div>
      <h1 className="business-heading">Custom 3D printing <br/><i>in Sydney.</i></h1>
      <div className="hero-brief"><p className="hero-service">Personalised favours, keepsakes <br/>and gifts, from 10 units.</p><p>We make event favours, religious keepsakes, corporate gifts and custom parts for businesses, parishes and families, and deliver them anywhere in Australia.</p><div className="actions"><a className="primary" href="/enquiry">Get a quote <span>↗</span></a><a className="secondary" href="#work">See our work ↓</a></div><MockupNote/></div>
      <div className="cinema-caption"><span>A PRINT IN PROGRESS</span><span>SCROLL TO WATCH ↓</span></div>
    </section>
    <section className="story-stage block-glass" id="b2b"><Chapter number="01" label="BULK & TRADE"/><div className="story-columns"><h2>Bulk 3D printing, <br/><em>from 10 units.</em></h2><article className="chapter-copy"><p>Shops, event planners, parishes and businesses order from us in batches. Every piece can share the same design, or each one can carry its own name or message.</p><p>Tell us what you want made, how many you need and when you need them. We’ll get back to you to work through the details and put a quote together.</p><div className="batch-detail"><b>10<span>+</span></b><p>Units per order. <br/>Your quote covers design, finish and timing.</p></div><a className="studio-text-link" href="/enquiry?route=supply">Ask about a bulk order <span>↗</span></a></article></div></section>
    <section className="floating-work block-solid" id="work"><Chapter number="02" label="OUR WORK"/><div className="story-section-heading"><h2>Some of our <br/><em>3D printed work.</em></h2><a className="studio-text-link" href="/work">See all our work ↗</a></div><div className="studio-gallery">{gallery.map((item, index) => { const photo = media[item.key]; return <a key={item.key} className={'studio-project project-' + item.key} href={'/work/' + item.slug}><img src={photo.src} srcSet={`${photo.src.replace('.webp', '-small.webp')} ${photo.smallWidth}w, ${photo.src} ${photo.width}w`} sizes="(max-width: 700px) 88vw, (max-width: 1100px) 44vw, 52vw" alt={photo.alt} width={photo.width} height={photo.height} loading="lazy"/><div className="project-caption"><span>{item.label}</span><h3>{item.title}</h3><b aria-hidden="true">↗</b></div><span className="project-index">0{index + 1} / 03</span></a>; })}</div><p className="studio-social"><a href="https://www.instagram.com/impeccablesculptures/" target="_blank" rel="noreferrer">More of our work on Instagram ↗</a></p></section>
    <section className="story-stage block-glass" id="events"><Chapter number="03" label="EVENTS & KEEPSAKES"/><div className="story-columns"><h2>Personalised <br/>event favours <br/><em>and keepsakes.</em></h2><article className="chapter-copy"><p>We make <a href="/pages/bonbonniere-custom">bonbonniere and religious keepsakes</a> for weddings, christenings and baptisms, and <a href="/pages/events-custom-gifts">corporate gifts and event favours</a> for businesses. Pieces can be personalised with names, dates or a short message.</p><dl className="studio-notes"><div><dt>01 / Personalisation</dt><dd>Names, dates, wording and colours.</dd></div><div><dt>02 / Packaging</dt><dd>Ask us about boxes, ribbon and tags.</dd></div><div><dt>03 / Timing</dt><dd>Your guest count and the date you need them by.</dd></div></dl><a className="studio-button" href="/enquiry?route=bulk">Enquire about event favours <span>↗</span></a></article></div></section>
    <section className="story-stage block-solid" id="supply"><Chapter number="04" label="REPEAT ORDERS"/><div className="story-columns"><div><h2>Repeat orders <br/><em>and ongoing supply.</em></h2><p className="heading-note">If you’ll need more batches later, for a shop or an annual event, mention it when you first get in touch.</p></div><article className="supply-ledger"><div><span>01</span><h3>Bulk &amp; trade</h3><p>A single batch for your shop, your clients or your organisation.</p></div><div><span>02</span><h3>Repeat production</h3><p>Reorder the same design, or change the wording or colours for the next batch.</p></div><div><span>03</span><h3>Supply arrangements</h3><p>Send us your expected yearly quantities, delivery schedule and any supplier paperwork you need.</p></div><a className="studio-button" href="/enquiry?route=supply">Talk to us about supply <span>↗</span></a></article></div></section>
    <section className="story-stage block-glass" id="printing"><Chapter number="05" label="PARTS & 3D FILES"/><div className="story-columns"><h2>Have a 3D file? <br/><em>We can print it.</em></h2><article className="chapter-copy"><div className="file-formats" aria-label="3D model formats">.STL <span>/</span> .OBJ <span>/</span> .3MF</div><p>We print parts, prototypes, jigs and custom objects. Send the model with its dimensions and what it’s for, and we’ll work out the best way to print it.</p><a className="studio-button" href="/enquiry?route=file">Send us your file <span>↗</span></a><a className="studio-text-link" href="/enquiry?route=design">No file yet? Start with your idea ↗</a></article></div><div className="mockup-offer"><span className="mockup-flag">FREE DESIGN MOCKUP</span><div><h3>Free design mockup with your quote</h3><p>Send us your idea and we’ll put together a digital mockup of the design with your quote. It’s free, and you don’t have to go ahead with the order.</p></div><a className="studio-button" href="/enquiry?route=design">Request a free design mockup <span>↗</span></a></div></section>
    <section className="floating-process block-solid" id="process"><Chapter number="06" label="HOW IT WORKS"/><div className="process-layout"><h2>How ordering <br/><em>works.</em></h2><ol className="studio-process"><li><span>01</span><h3>Send your brief</h3><p>Tell us what it’s for, how many you need and your deadline. You don’t need a finished design.</p></li><li><span>02</span><h3>Get your quote</h3><p>We’ll agree the price and timing with you. If you’re starting from an idea, we’ll include a free design mockup.</p></li><li><span>03</span><h3>Approve and print</h3><p>Once you’ve approved the design, we start printing.</p></li></ol></div></section>
    <section className="floating-guides block-glass" id="guides"><Chapter number="07" label="GUIDES"/><div className="story-section-heading"><h2>Guides for <br/><em>planning an order.</em></h2><a className="studio-text-link" href="/guides">Read all our guides ↗</a></div><GuideGrid items={[guides[0], guides[3]]}/></section>
    <section className="story-stage faq-stage block-solid" id="faq"><Chapter number="08" label="FAQ"/><div className="story-columns"><h2>Frequently asked <br/><em>questions.</em></h2><div className="faq-list"><details><summary>What’s the minimum order?</summary><p>10 units. The price per piece depends on the size, finish and how much design work is involved. For a single piece, have a look at our Etsy shop.</p></details><details><summary>Can you meet an event deadline?</summary><p>Tell us the date you need everything in hand. We’ll check it against design approval, printing and shipping, and let you know if it works before you commit.</p></details><details><summary>Can I reorder the same design?</summary><p>Yes. Let us know roughly how many you’d need per batch and per year so we can plan for it.</p></details><details><summary>Do I need a 3D file?</summary><p>No. A description, rough measurements and a few reference photos are enough to get started. If design work is needed, it’ll be included in your quote.</p></details><details><summary>Can I see the design before I order?</summary><p>Yes. Send us your idea and we’ll put together a free design mockup with your quote. You don’t have to go ahead with the order.</p></details><details><summary>Do you deliver across Australia?</summary><p>Yes. Freight is quoted based on your order and where it’s going.</p></details></div></div></section>
    <section className="story-stage testimonial-stage block-glass" id="testimonials"><Chapter number="09" label="REVIEWS"/><div className="story-section-heading"><h2>Customer <br/><em>reviews.</em></h2><p>Reviews from Google, Etsy and Judge.me.</p></div><div className="testimonial-grid">{reviews.map(review => <figure className="testimonial-card" key={review.id}><div className="testimonial-rating" role="img" aria-label={`${review.rating} out of 5 stars`}><span aria-hidden="true">★★★★★</span></div><blockquote>“{review.quote}”</blockquote><figcaption><strong>{review.author}</strong><span>{review.role}</span><small>{SOURCE_LABELS[review.source]}</small></figcaption></figure>)}</div></section>
  </main>;
}
