import PrinterBackdrop from './components/printer-backdrop';
import ChapterNavigation from './components/chapter-navigation';
import GuideGrid from './components/guide-grid';
import { guides } from '../content/guides';
import media from '../content/work-media.json';

const gallery = [
  { key: 'custom-sculptures', slug: 'custom-sculptures-keepsakes', title: 'Objects with character', label: 'CUSTOM SCULPTURES' },
  { key: 'event-favours', slug: 'ribbon-finished-event-favours', title: 'Made for the occasion', label: 'EVENT KEEPSAKES' },
  { key: 'yellow-rose-sculptures', slug: 'personalised-rose-sculptures', title: 'A brighter kind of keepsake', label: 'CUSTOM ART & KEEPSAKES' },
] as const;
function Chapter({ number, label }: { number: string; label: string }) { return <div className="chapter-marker"><span>{number}</span><span>{label}</span></div>; }

export default function Home() {
  return <main id="main-content" className="cinematic-home sculpture-story">
    <PrinterBackdrop/><ChapterNavigation/>
    <section className="hero cinema-hero" id="top">
      <div className="eyebrow">IMPECCABLE SCULPTURES / SYDNEY STUDIO</div>
      <h1 className="business-heading">Made for<br/><i>more than one.</i></h1>
      <div className="hero-brief"><p className="hero-service">Custom 3D printing.<br/>Bulk orders. Individual character.</p><p>For businesses, events and communities. From personalised keepsakes to the next production run.</p><div className="actions"><a className="primary" href="/enquiry">Start your project <span>↗</span></a><a className="secondary" href="#work">Explore our work ↓</a></div></div>
      <div className="cinema-caption"><span>AN IDEA TAKES SHAPE</span><span>SCROLL TO BUILD ↓</span></div>
      <div className="hero-order-note"><b>10<span>+</span></b><span>UNITS TO START<br/>YOUR NEXT BATCH</span></div>
    </section>
    <section className="story-stage block-glass" id="b2b"><Chapter number="01" label="MADE IN MULTIPLES"/><div className="story-columns"><h2>One idea.<br/>Made in<br/><em>multiples.</em></h2><article className="chapter-copy"><p>For your customers, your guests or your community. A batch can share a design and still carry the details that make it yours.</p><p>Tell us what you have in mind, how many you need and when. We’ll review the design and production brief together.</p><div className="batch-detail"><b>10<span>+</span></b><p>Units per bulk order.<br/>Design, finish and timing confirmed with your quote.</p></div><a className="studio-text-link" href="/enquiry?route=supply">Start a bulk or trade enquiry <span>↗</span></a></article></div></section>
    <section className="floating-work block-solid" id="work"><Chapter number="02" label="FROM THE STUDIO"/><div className="story-section-heading"><h2>A few<br/><em>possibilities.</em></h2><a className="studio-text-link" href="/work">Explore all work ↗</a></div><div className="studio-gallery">{gallery.map((item, index) => { const photo = media[item.key]; return <a key={item.key} className={'studio-project project-' + item.key} href={'/work/' + item.slug}><img src={photo.src} srcSet={`${photo.src.replace('.webp', '-small.webp')} ${photo.smallWidth}w, ${photo.src} ${photo.width}w`} sizes="(max-width: 700px) 88vw, (max-width: 1100px) 44vw, 52vw" alt={photo.alt} width={photo.width} height={photo.height} loading="lazy"/><div className="project-caption"><span>{item.label}</span><h3>{item.title}</h3><b aria-hidden="true">↗</b></div><span className="project-index">0{index + 1} / 03</span></a>; })}</div><p className="studio-social"><a href="https://www.instagram.com/impeccablesculptures/" target="_blank" rel="noreferrer">More from the studio on Instagram ↗</a></p></section>
    <section className="story-stage block-glass" id="events"><Chapter number="03" label="FOR THE OCCASION"/><div className="story-columns"><h2>A moment.<br/>Something<br/><em>to keep.</em></h2><article className="chapter-copy"><p>Bonbonniere, personalised keepsakes and corporate gifts. Bring the meaning of the occasion into the piece itself.</p><dl className="studio-notes"><div><dt>01 / The detail</dt><dd>Names, dates, wording and colours.</dd></div><div><dt>02 / The presentation</dt><dd>Discuss boxes, ribbons and packaging.</dd></div><div><dt>03 / The occasion</dt><dd>Your guest count and required delivery date.</dd></div></dl><a className="studio-button" href="/enquiry?route=bulk">Plan an event order <span>↗</span></a></article></div></section>
    <section className="story-stage block-solid" id="supply"><Chapter number="04" label="BEYOND THE FIRST RUN"/><div className="story-columns"><div><h2>The next run.<br/><em>And the next.</em></h2><p className="heading-note">For retailers, planners and businesses.<br/>Start with the order. Talk about what follows.</p></div><article className="supply-ledger"><div><span>01</span><h3>Bulk & trade</h3><p>A one-off batch for your customers, clients or organisation.</p></div><div><span>02</span><h3>Repeat production</h3><p>Discuss quantities, versions and the details to carry into the next run.</p></div><div><span>03</span><h3>Supply arrangements</h3><p>Share forecasts, delivery schedules and supplier requirements for review.</p></div><a className="studio-button" href="/enquiry?route=supply">Discuss business supply <span>↗</span></a></article></div></section>
    <section className="story-stage block-glass" id="printing"><Chapter number="05" label="FROM IDEA TO OBJECT"/><div className="story-columns"><h2>From a file.<br/>To something<br/><em>you can hold.</em></h2><article className="chapter-copy"><div className="file-formats" aria-label="3D model formats">.STL <span>/</span> .OBJ <span>/</span> .3MF</div><p>A part, a prototype or a custom object. Share the model, dimensions and intended use so we can review the material and production requirements.</p><a className="studio-button" href="/enquiry?route=file">Enquire with a 3D file <span>↗</span></a><a className="studio-text-link" href="/enquiry?route=design">No file yet? Start with your idea ↗</a></article></div><aside className="mockup-offer"><span className="mockup-flag">FREE MOCKUP</span><div><h3>See it before you commit.</h3><p>Send us your idea and we’ll prepare a digital mockup of the design alongside your quote — free, with no obligation to order.</p></div><a className="studio-button" href="/enquiry?route=design">Request a free mockup <span>↗</span></a></aside></section>
    <section className="floating-process block-solid" id="process"><Chapter number="06" label="THE NEXT STEPS"/><div className="process-layout"><h2>A clear way<br/><em>forward.</em></h2><ol className="studio-process"><li><span>01</span><h3>The brief</h3><p>Tell us the use, quantity and deadline. A finished design is optional.</p></li><li><span>02</span><h3>The details</h3><p>Agree the specification, pricing, timing and any design or sample costs.</p></li><li><span>03</span><h3>The batch</h3><p>Confirm the design and approval steps before production begins.</p></li></ol></div></section>
    <section className="floating-guides block-glass" id="guides"><Chapter number="07" label="PLAN YOUR PROJECT"/><div className="story-section-heading"><h2>Before<br/><em>we begin.</em></h2><a className="studio-text-link" href="/guides">All studio guides ↗</a></div><GuideGrid items={[guides[0], guides[3]]}/></section>
    <section className="story-stage faq-stage block-solid" id="faq"><Chapter number="08" label="A FEW USEFUL ANSWERS"/><div className="story-columns"><h2>Good<br/><em>questions.</em></h2><div className="faq-list"><details><summary>What is the minimum order?</summary><p>Bulk orders start at 10 units. Pricing depends on the product, size, finish and design work involved.</p></details><details><summary>Can you work to an event deadline?</summary><p>Tell us when you need the items delivered. We’ll review capacity, approvals and shipping before confirming a timeframe.</p></details><details><summary>Can I order the same design again?</summary><p>Repeat order and ongoing supply enquiries are welcome. Include your likely quantity per batch and estimated annual demand.</p></details><details><summary>Do I need a 3D file?</summary><p>No. Start with a description, dimensions and reference images. Design requirements and approval stages are confirmed with your quote.</p></details><details><summary>Do you deliver across Australia?</summary><p>Australia-wide delivery is available. Freight, packaging and timing are confirmed for your order and destination.</p></details></div></div></section>
  </main>;
}
